apiVersion: v1
kind: Secret
metadata:
  name: devicestatus-secret
  namespace: devicestatus
type: Opaque
stringData:
  # These will be automatically base64 encoded
  DB_URL: "jdbc:postgresql://devicestatus-db.cb8cgs84gdsk.ap-south-1.rds.amazonaws.com:5432/devicestatus"
  DB_USERNAME: "devicestatus"
  DB_PASSWORD: "DevStatus2024!"
